- hosts: 0.0.0.0
  vars_prompt: 
          -  name: folder_dir
             private: no
             prompt: "Please type Hadoop folder directory: -"

          -  name: master_ip_add
             private: no
             prompt: "Please enter NameNode Ip Address : -"
  tasks:
          - file: 
              path: /
              state: directory
          - copy: 
              src: hadoop-1.2.1-1.x86_64.rpm  
              dest: / 
          - copy: 
              src: jdk-8u171-linux-x64.rpm
              dest: /

          - name: Install JDK
            yum:
              name: /jdk-8u171-linux-x64.rpm
              state: present

          - name: install hadoop
            shell: rpm -i --force /hadoop-1.2.1-1.x86_64.rpm
            register: Hadoop
            ignore_errors: yes

          - name: Editing HDFS-site.xml file
            blockinfile: 
              path: /etc/hadoop/hdfs-site.xml
              insertafter: "<configuration>"
              content: |
                <property>
                <name>dfs.data.dir</name>
                <value>/{{ folder_dir }}</value>
                </property>
          - name: Editing Core-site.xml file
            blockinfile: 
              path: /etc/hadoop/core-site.xml
              insertafter: "<configuration>"
              content: |
                <property>
                <name>fs.default.name</name>
                <value>hdfs://{{ master_ip_add }}:9001</value>
                </property>

          - name: Stop existing dataNode
            shell: "hadoop-daemon.sh stop datanode"
          - name: Starting DataNode
            shell: "hadoop-daemon.sh start datanode"
          - name: Java process
            shell: "jps" 
