- hosts: all
  tasks:
  - yum_repository:
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
      name: "docker"
      description: "dvd1 for Docker"
      gpgcheck: no

  - file: 
      path: /webserver
      state: directory
  - copy: 
      src: index.html
      dest: /webserver

  - pip:
      name: "docker"
      
  - package:
      name: "docker-ce-18.09.1-3.el7.x86_64"
      state: present
      skip_broken: yes

  - service:
      name: "docker"
      state: started

  - docker_image:
      name: "httpd"
      source: pull

  - docker_container:
      name: webserver
      image: httpd:latest
      exposed_ports: "80"
      ports: "8080:80"
      volumes: "/webserver:/usr/local/apache2/htdocs"
