- hosts: 'FrontEnd'
  tasks:
          - name: Installing HaProxy
            package:
              name: haproxy
              state: present
          - name: 'Replacing bind port with 8080'
            replace:
              path: /etc/haproxy/haproxy.cfg
              regexp: ":5000"
              replace: ":8080"
          - name: 'Removing localhost from BachEnd app '
            lineinfile:
               path: /etc/haproxy/haproxy.cfg
               regexp: '{{item.From}}'
               line: '{{item.To}}'
               state: present
            with_items:
                    - { From: '127.0.0.1:5001', To: '' }
                    - { From: '127.0.0.1:5002', To: '' }
                    - { From: '127.0.0.1:5003', To: '' }
                    - { From: '127.0.0.1:5004', To: '' }
                    - { From: 'balance     roundrobin', To: '' }
          - name: 'Adding Ip address in config file'
            blockinfile:
               path: /etc/haproxy/haproxy.cfg
               insertafter: 'backend app'
               block: |
                       balance roundrobin
                       {% for i in groups['BackEnd'] %}
                       server app{{loop.index}} {{ i }}:80 check
                       {% endfor %}
          - name: 'Restarting Haproxy'
            service: 
               name: haproxy
               state: restarted
          - name: Stopping firewalld
            service:
               name: firewalld
               state: stopped
